import type {
  DriverCustomer,
  DriverOrder,
  DriverProfile,
  DriverIncident,
  JornadaCierre,
  RouteVisitStatus,
} from "./types";

/** Fecha operativa demo (alinear con seeds) */
export const DRIVER_TODAY = "2026-03-27";

export const driverProfileSeed: DriverProfile = {
  name: "Roberto Conductor",
  email: "driver@demo.local",
  phone: "+1 786 000 2200",
  vehicleLabel: "Van blanca · Ruta Norte",
};

export const driverCustomersSeed: DriverCustomer[] = [
  {
    id: "dc1",
    businessName: "Bodega La 9",
    contactName: "Carlos Perez",
    phone: "+17865550100",
    address: "NW 12th St, Miami",
    zone: "Zona A",
    gpsLink: "https://maps.google.com/?q=25.78,-80.23",
    visitOrder: 1,
  },
  {
    id: "dc2",
    businessName: "Mini Market Sol",
    contactName: "Ana Ruiz",
    phone: "+17865550200",
    address: "Calle 8, Hialeah",
    zone: "Zona B",
    gpsLink: "https://maps.google.com/?q=25.84,-80.28",
    visitOrder: 2,
  },
  {
    id: "dc3",
    businessName: "Colmado El Progreso",
    contactName: "Luis Gomez",
    phone: "+17865550300",
    address: "Flagler St, Miami",
    zone: "Zona A",
    gpsLink: "https://maps.google.com/?q=25.77,-80.19",
    visitOrder: 3,
  },
  {
    id: "dc4",
    businessName: "Abasto Express",
    contactName: "Rosa M.",
    phone: "+17865550400",
    address: "Kendall",
    zone: "Zona C",
    gpsLink: "https://maps.google.com/?q=25.67,-80.35",
    visitOrder: 4,
  },
];

/** Estado inicial de visita por cliente (clave = customerId) */
export const routeVisitStatusSeed: Record<string, RouteVisitStatus> = {
  dc1: "pendiente",
  dc2: "en_ruta",
  dc3: "pendiente",
  dc4: "reagendado",
};

/**
 * Varios pedidos confirmados el mismo día: mismo cliente con 2 pedidos (dc1),
 * otros repartidos.
 */
export const driverOrdersSeed: DriverOrder[] = [
  {
    id: "do1",
    customerId: "dc1",
    status: "confirmado",
    paymentStatus: "pendiente",
    amountPaid: 0,
    createdAt: DRIVER_TODAY,
    note: "Entregar antes del mediodia",
    lines: [
      {
        productId: "p1",
        productName: "Arroz 1kg",
        qtyOrdered: 20,
        qtyPurchased: 20,
        qtyDelivered: 0,
        unitSalePrice: 2.5,
        unitCostEstimate: 1.85,
        unitCostReal: 1.82,
        purchaseStatus: "comprado",
        deliveryStatus: "pendiente",
        supplier: "Mayorista Central",
      },
      {
        productId: "p2",
        productName: "Aceite 1L",
        qtyOrdered: 6,
        qtyPurchased: 4,
        qtyDelivered: 0,
        unitSalePrice: 4.2,
        unitCostEstimate: 3.1,
        unitCostReal: 3.05,
        purchaseStatus: "parcial",
        deliveryStatus: "pendiente",
        supplier: "Mayorista Central",
        purchaseNote: "Faltaron 2 unidades",
      },
    ],
  },
  {
    id: "do2",
    customerId: "dc1",
    status: "confirmado",
    paymentStatus: "pendiente",
    amountPaid: 0,
    createdAt: DRIVER_TODAY,
    lines: [
      {
        productId: "p3",
        productName: "Pasta 500g",
        qtyOrdered: 24,
        qtyPurchased: 0,
        qtyDelivered: 0,
        unitSalePrice: 1.9,
        unitCostEstimate: 1.2,
        purchaseStatus: "pendiente",
        deliveryStatus: "pendiente",
      },
      {
        productId: "p6",
        productName: "Leche entera 1L",
        qtyOrdered: 12,
        qtyPurchased: 12,
        qtyDelivered: 0,
        unitSalePrice: 3.1,
        unitCostEstimate: 2.4,
        purchaseStatus: "comprado",
        deliveryStatus: "pendiente",
        supplier: "Lacteos del Este",
      },
    ],
  },
  {
    id: "do3",
    customerId: "dc2",
    status: "listo_ruta",
    paymentStatus: "parcial",
    amountPaid: 40,
    createdAt: DRIVER_TODAY,
    lines: [
      {
        productId: "p1",
        productName: "Arroz 1kg",
        qtyOrdered: 10,
        qtyPurchased: 10,
        qtyDelivered: 10,
        unitSalePrice: 2.5,
        unitCostEstimate: 1.85,
        unitCostReal: 1.85,
        purchaseStatus: "comprado",
        deliveryStatus: "entregado",
        supplier: "Mayorista Central",
      },
      {
        productId: "p4",
        productName: "Azucar 1kg",
        qtyOrdered: 8,
        qtyPurchased: 0,
        qtyDelivered: 0,
        unitSalePrice: 2.2,
        unitCostEstimate: 1.5,
        purchaseStatus: "no_encontrado",
        deliveryStatus: "no_entregado",
        purchaseNote: "Sin stock en ruta matutina",
      },
    ],
  },
  {
    id: "do4",
    customerId: "dc3",
    status: "confirmado",
    paymentStatus: "pendiente",
    amountPaid: 0,
    createdAt: DRIVER_TODAY,
    lines: [
      {
        productId: "p2",
        productName: "Aceite 1L",
        qtyOrdered: 12,
        qtyPurchased: 0,
        qtyDelivered: 0,
        unitSalePrice: 4.2,
        unitCostEstimate: 3.1,
        purchaseStatus: "pendiente",
        deliveryStatus: "pendiente",
      },
      {
        productId: "p5",
        productName: "Harina PAN",
        qtyOrdered: 30,
        qtyPurchased: 30,
        qtyDelivered: 0,
        unitSalePrice: 1.8,
        unitCostEstimate: 1.1,
        unitCostReal: 1.12,
        purchaseStatus: "comprado",
        deliveryStatus: "pendiente",
        supplier: "Mayorista Central",
        substitutionProductName: undefined,
      },
    ],
  },
  {
    id: "do5",
    customerId: "dc2",
    status: "confirmado",
    paymentStatus: "pendiente",
    amountPaid: 0,
    createdAt: DRIVER_TODAY,
    lines: [
      {
        productId: "p3",
        productName: "Pasta 500g",
        qtyOrdered: 12,
        qtyPurchased: 0,
        qtyDelivered: 0,
        unitSalePrice: 1.9,
        unitCostEstimate: 1.2,
        purchaseStatus: "pendiente",
        deliveryStatus: "pendiente",
      },
    ],
  },
];

export const incidentsSeed: DriverIncident[] = [
  {
    id: "di1",
    at: `${DRIVER_TODAY}T09:15:00`,
    type: "producto_no_encontrado",
    description: "Azucar 8kg no disponible en primer almacen",
    customerId: "dc2",
    orderId: "do3",
    resolution: "abierta",
    recordedBy: driverProfileSeed.name,
  },
];

export const jornadaHistorySeed: JornadaCierre[] = [
  {
    id: "jc0",
    date: "2026-03-26",
    closedAt: "2026-03-26T18:30:00",
    note: "Lluvia tarde, un cliente reprogramado",
    stats: {
      pedidosAsignados: 6,
      pedidosEntregados: 5,
      pedidosParciales: 1,
      pedidosNoEntregados: 0,
      totalVenta: 1240,
      totalCompraReal: 890,
      totalCobrado: 1180,
      cobradoEfectivo: 700,
      cobradoDigital: 480,
      totalPendiente: 60,
      incidencias: 1,
    },
  },
];
